server:
  port: 9001
spring:
  profiles:
      active: dev
  dubbo:
    application:
      name: dubbo-provider

#设置采用的服务协议
    protocol:
      name: dubbo
      port: 20880
# 设置当前项目当中使用dubbo注解的包路径
    scan: com.dubbo.demo