server:
  port: 9002
spring:
  profiles:
    active: dev
  dubbo:
    # 设置当前项目当中使用dubbo注解的包路径
    scan: com.dubbo.demo
    application:
      name: dubbo-consumer
  #   设置zk的服务端口
    registry:
      address: zookeeper://192.168.99.100:2181

  main:
    allow-bean-definition-overriding: true

